# Generated by Django 4.0 on 2021-12-15 16:35

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocalProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', users.models.ReadOnlyCrossDatabaseField(verbose_name='users.UserProxy')),
            ],
        ),
    ]
