# Generated by Django 4.0 on 2021-12-15 16:51

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlocalproxy',
            name='users',
        ),
        migrations.AddField(
            model_name='userlocalproxy',
            name='user_proxy',
            field=users.models.SimpleCrossDatabaseField(default=None, to="users.models.UserProxy", remote_db="users"),
            preserve_default=False,
        ),
    ]
